---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: awx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: awx
    app: awx
spec:
  destination:
    namespace: awx
    name: "https://kubernetes.default.svc"
  project: default
  source:
    path: apps
    repoURL: https://github.com/shrapk2/argo-awx-application
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
