---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: awx
spec:
  project: default
  source:
    repoURL: https://github.com/shrapk2/argo-awx-application
    targetRevision: HEAD
    path: apps
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
