---
apiVersion: v1
kind: Secret
metadata:
  name: bitnami-helm-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami-helm-repository
  url: https://charts.bitnami.com/bitnami
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: kyverno-helm-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: kyverno-helm-repository
  url: https://kyverno.github.io/kyverno/
  type: helm

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-services
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Core Services Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: "grafana"
      name: "in-cluster"
    - namespace: "argocd"
      name: "in-cluster"
    - namespace: "prometheus"
      name: "in-cluster"
    - namespace: "metrics-server"
      name: "in-cluster"
    - namespace: "cert-manager"
      name: "in-cluster"
    - namespace: "external-dns"
      name: "in-cluster"
    - namespace: "kyverno"
      name: "in-cluster"
    - namespace: "kube-system"
      name: "in-cluster"
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-services
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: core-services
spec:
  project: core-services
  source:
    repoURL: https://github.com/shrapk2/argo-awx-application
    targetRevision: demoapp
    path: apps
  destination:
    name: "in-cluster"
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
