---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: awx
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: AWX Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: 'awx'
    server: 'https://kubernetes.default.svc'

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: awx
spec:
  project: awx
  source:
    repoURL: https://github.com/shrapk2/argo-awx-application
    targetRevision: HEAD
    path: apps
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
