---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx
commonLabels:
  app: awx
resources:
  - application.yaml
  - apps/awx-operator.yaml
  - apps/awx-system.yaml
patchesStrategicMerge:
  - overlays/nonprod/stacks.yaml
