---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: microservices
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: microservices
  source:
    repoURL: "https://github.com/cetic/helm-microservice.git"
    targetRevision: master
    path: microservices
    helm:
      parameters:
        - name: ingress.hosts[0].host
          value: "microservice.example.com"
    # plugin:
    #   name: kustomized-helm
  destination:
    name: "in-cluster"
    namespace: microservices
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
