---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-system2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: awx2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: awx2
  source:
    repoURL: "https://github.com/shrapk2/awx-operator-helm"
    targetRevision: HEAD
    path: awx-system
    helm:
      parameters:
        - name: network.hostname
          value: "awx2.example.com"
    # plugin:
    #   name: kustomized-helm
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx2
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
