---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: awx
spec:
  project: default
  source:
    repoURL: "https://github.com/shrapk2/awx-operator-helm"
    targetRevision: HEAD
    path: awx-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
