---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: awx2
spec:
  project: awx2
  source:
    repoURL: "https://github.com/shrapk2/awx-operator-helm"
    targetRevision: HEAD
    path: awx-operator
  destination:
    name: "in-cluster"
    namespace: awx2
    # plugin:
    #   name: kustomized-helm
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
