---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: core-services
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 6.0.2
    chart: external-dns
    # helm:
    #   parameters:
    #     - name: ingress.hosts[0].host
    #       value: "microservice.example.com"
  destination:
    name: "in-cluster"
    namespace: external-dns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
